import type { TranslationConfig } from "../../../../app/modules/language/domain/translation";

export const KEYWORDS: TranslationConfig<string[]> = {
  es: [
    "visa para Cuba",
    "visado Cuba",
    "solicitar visa Cuba online",
    "visado turístico Cuba",
    "requisitos visa Cuba",
    "tramitar visa para Cuba",
    "visa cubana urgente",
    "formulario visa Cuba",
    "agencia de visado Cuba",
    "visado electrónico Cuba",
    "viajar a Cuba",
    "turismo en Cuba",
    "vacaciones en Cuba",
    "vuelos a Cuba",
    "alojamiento en Cuba",
    "seguro médico para Cuba",
    "viaje a La Habana",
    "cómo viajar a Cuba legalmente",
  ],
  en: [
    "Cuba visa",
    "Cuba tourist visa",
    "apply for Cuba visa online",
    "Cuba travel authorization",
    "Cuba eVisa",
    "Cuba visa requirements",
    "Cuba entry form",
    "how to travel to Cuba",
    "Cuba tourist card",
    "Cuba travel guide",
    "travel to Cuba from USA",
    "Cuba visa for tourists",
    "Cuba visa online application",
    "best places to visit in Cuba",
    "flights to Havana",
    "Cuban travel agency",
    "holidays in Cuba",
    "Cuba vacation",
  ],
  it: [
    "visto per Cuba",
    "visto turistico Cuba",
    "richiesta visto Cuba online",
    "documenti per visto Cuba",
    "modulo richiesta visto Cuba",
    "come ottenere il visto per Cuba",
    "visto elettronico Cuba",
    "agenzia visti Cuba",
    "viaggiare a Cuba",
    "vacanze a Cuba",
    "turismo a L'Avana",
    "biglietti per Cuba",
    "assicurazione viaggio Cuba",
    "migliori spiagge di Cuba",
    "guida di viaggio Cuba",
    "Cuba visto online",
    "visto urgente Cuba",
  ],
};
