export const APP_IMAGES = {
  LOGO: { src: "/images/logo.png", alt: "Logo" },
  FOOTER_LOGO: { src: "/images/logo-footer.png", alt: "Footer logo" },
  CUBA_1: { src: "/images/cuba-1.webp", alt: "cuba-1" },
  CUBA_2: { src: "/images/cuba-2.webp", alt: "cuba-2" },
  CUBA_3: { src: "/images/cuba-3.webp", alt: "cuba-3" },
  CUBA_4: { src: "/images/cuba-4.webp", alt: "cuba-4" },
  HEALTH: { src: "/images/health.webp", alt: "health" },
  BEACH: { src: "/images/beach.webp", alt: "beach" },
  DOCTOR: { src: "/images/doctor.webp", alt: "doctor" },
  PASSPORTS: { src: "/images/passports.webp", alt: "passports" },
  CUBA_FLAG: { src: "/images/cuba-flag.webp", alt: "cuba-flag" },
  BLOG: {
    ROOT: { src: "/images/blog/blog.webp" },
    ARTICLES: { VISA_ELECTRONIC: { src: "/images/blog/visa-electronic.webp" } },
  },
  BANNER1: { src: "/images/banner1.png", alt: "happy-woman" },
  BANNER2: { src: "/images/banner2.png", alt: "front-woman" },
  OPINION: {
    FIRST: { src: "/images/opinions/1.png", alt: "first-opinion" },
    SECOND: { src: "/images/opinions/2.png", alt: "second-opinion" },
    THIRD: { src: "/images/opinions/3.png", alt: "third-opinion" },
  },
  FLAGS: { CUBA: { src: "/images/flags/cuba.svg", alt: "cuba" } },
};
