// Definimos la interfaz para representar un país
interface Country {
  name: string;
}

// Creamos el arreglo con todos los países reconocidos por la ONU
export const COUNTRIES: Country[] = [
  // América del Norte
  { name: "Antigua y Barbuda" },
  { name: "Bahamas" },
  { name: "Barbados" },
  { name: "Belice" },
  { name: "Canadá" },
  { name: "Costa Rica" },
  { name: "Cuba" },
  { name: "Dominica" },
  { name: "República Dominicana" },
  { name: "El Salvador" },
  { name: "Estados Unidos" },
  { name: "Granada" },
  { name: "Guatemala" },
  { name: "Haití" },
  { name: "Honduras" },
  { name: "Jamaica" },
  { name: "México" },
  { name: "Nicaragua" },
  { name: "Panamá" },
  { name: "San Cristóbal y Nieves" },
  { name: "Santa Lucía" },
  { name: "San Vicente y las Granadinas" },
  { name: "Trinidad y Tobago" },

  // América Central y del Sur
  { name: "Argentina" },
  { name: "Bolivia" },
  { name: "Brasil" },
  { name: "Chile" },
  { name: "Colombia" },
  { name: "Ecuador" },
  { name: "Guyana" },
  { name: "Paraguay" },
  { name: "Perú" },
  { name: "Surinam" },
  { name: "Uruguay" },
  { name: "Venezuela" },

  // Europa
  { name: "Alemania" },
  { name: "Andorra" },
  { name: "Armenia" },
  { name: "Austria" },
  { name: "Azerbaiyán" },
  { name: "Bélgica" },
  { name: "Bielorrusia" },
  { name: "Bosnia y Herzegovina" },
  { name: "Bulgaria" },
  { name: "Croacia" },
  { name: "Chipre" },
  { name: "Dinamarca" },
  { name: "Eslovaquia" },
  { name: "Eslovenia" },
  { name: "España" },
  { name: "Estonia" },
  { name: "Finlandia" },
  { name: "Francia" },
  { name: "Georgia" },
  { name: "Grecia" },
  { name: "Hungría" },
  { name: "Irlanda" },
  { name: "Islandia" },
  { name: "Italia" },
  { name: "Kazajistán" },
  { name: "Kirguizistán" },
  { name: "Letonia" },
  { name: "Liechtenstein" },
  { name: "Lituania" },
  { name: "Luxemburgo" },
  { name: "Malta" },
  { name: "Moldavia" },
  { name: "Mónaco" },
  { name: "Montenegro" },
  { name: "Noruega" },
  { name: "Países Bajos" },
  { name: "Polonia" },
  { name: "Portugal" },
  { name: "Reino Unido" },
  { name: "República Checa" },
  { name: "Rumania" },
  { name: "Rusia" },
  { name: "San Marino" },
  { name: "Serbia" },
  { name: "Suecia" },
  { name: "Suiza" },
  { name: "Turquía" },
  { name: "Ucrania" },
  { name: "Ciudad del Vaticano" },

  // África
  { name: "Angola" },
  { name: "Argelia" },
  { name: "Benín" },
  { name: "Botsuana" },
  { name: "Burkina Faso" },
  { name: "Burundi" },
  { name: "Cabo Verde" },
  { name: "Camerún" },
  { name: "República Centroafricana" },
  { name: "Chad" },
  { name: "Comoras" },
  { name: "Congo" },
  { name: "Congo (República Democrática)" },
  { name: "Costa de Marfil" },
  { name: "Egipto" },
  { name: "Eritrea" },
  { name: "Eswatini" },
  { name: "Etiopía" },
  { name: "Gabón" },
  { name: "Gambia" },
  { name: "Ghana" },
  { name: "Guinea" },
  { name: "Guinea-Bissau" },
  { name: "Guinea Ecuatorial" },
  { name: "Kenia" },
  { name: "Lesoto" },
  { name: "Liberia" },
  { name: "Libia" },
  { name: "Madagascar" },
  { name: "Malawi" },
  { name: "Malí" },
  { name: "Mauritania" },
  { name: "Mauricio" },
  { name: "Marruecos" },
  { name: "Mozambique" },
  { name: "Namibia" },
  { name: "Níger" },
  { name: "Nigeria" },
  { name: "Ruanda" },
  { name: "Santo Tomé y Príncipe" },
  { name: "Senegal" },
  { name: "Sierra Leona" },
  { name: "Somalia" },
  { name: "Sudáfrica" },
  { name: "Sudán" },
  { name: "Sudán del Sur" },
  { name: "Tanzania" },
  { name: "Togo" },
  { name: "Túnez" },
  { name: "Uganda" },
  { name: "Yibuti" },
  { name: "Zambia" },
  { name: "Zimbabue" },

  // Asia
  { name: "Afganistán" },
  { name: "Arabia Saudita" },
  { name: "Bangladés" },
  { name: "Baréin" },
  { name: "Birmania" },
  { name: "Brunéi" },
  { name: "Bután" },
  { name: "Camboya" },
  { name: "Catar" },
  { name: "China" },
  { name: "Chipre" },
  { name: "Corea del Norte" },
  { name: "Corea del Sur" },
  { name: "Emiratos Árabes Unidos" },
  { name: "Filipinas" },
  { name: "India" },
  { name: "Indonesia" },
  { name: "Irak" },
  { name: "Irán" },
  { name: "Israel" },
  { name: "Japón" },
  { name: "Jordania" },
  { name: "Kuwait" },
  { name: "Laos" },
  { name: "Líbano" },
  { name: "Malasia" },
  { name: "Maldivas" },
  { name: "Mongolia" },
  { name: "Nepal" },
  { name: "Omán" },
  { name: "Pakistán" },
  { name: "Palestina" },
  { name: "Singapur" },
  { name: "Siria" },
  { name: "Sri Lanka" },
  { name: "Tailandia" },
  { name: "Taiwán" },
  { name: "Timor Oriental" },
  { name: "Turkmenistán" },
  { name: "Uzbekistán" },
  { name: "Vietnam" },
  { name: "Yemen" },

  // Oceanía
  { name: "Australia" },
  { name: "Fiyi" },
  { name: "Islas Marshall" },
  { name: "Islas Salomón" },
  { name: "Kiribati" },
  { name: "Micronesia" },
  { name: "Nauru" },
  { name: "Nueva Zelanda" },
  { name: "Palaos" },
  { name: "Papúa Nueva Guinea" },
  { name: "Samoa" },
  { name: "Tonga" },
  { name: "Tuvalu" },
  { name: "Vanuatu" },
];
